#define MICROPY_HW_BOARD_NAME "SQUiXL"
#define MICROPY_HW_MCU_NAME "ESP32-S3-R8"
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "SQUiXL"

#define MICROPY_HW_I2C0_SCL (2)
#define MICROPY_HW_I2C0_SDA (1)

// #define MICROPY_HW_SPI1_MOSI (6)
// #define MICROPY_HW_SPI1_MISO (5)
// #define MICROPY_HW_SPI1_SCK (4)
